version: '3.8'

services:
  crm-app:
    build: .
    container_name: crm-produccion-comercial
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://crm_user:crm_secure_password@postgres-db:5432/crm_produccion?schema=public
      - JWT_SECRET=change_this_to_a_very_long_secure_random_key_ecuavisa
      - NODE_ENV=production
    volumes:
      - crm_uploads_data:/app/public/uploads
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16-alpine
    container_name: crm-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_PASSWORD=crm_secure_password
      - POSTGRES_DB=crm_produccion
    volumes:
      - crm_db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  crm_db_data:
  crm_uploads_data:
